-- Nano Marketer Pro Database Schema
-- PostgreSQL Schema for Neon Database

-- Table: campaigns
-- Stores marketing campaigns created by users
CREATE TABLE IF NOT EXISTS campaigns (
  id SERIAL PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  language VARCHAR(50) NOT NULL,
  brand_vibe TEXT,
  consistency_guide TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Table: assets
-- Stores individual marketing assets for each campaign
CREATE TABLE IF NOT EXISTS assets (
  id SERIAL PRIMARY KEY,
  campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  asset_id INTEGER NOT NULL,
  title VARCHAR(255) NOT NULL,
  phase VARCHAR(50) NOT NULL,
  prompt TEXT NOT NULL,
  description TEXT NOT NULL,
  aspect_ratio VARCHAR(10),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_campaigns_created_at ON campaigns(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_assets_campaign_id ON assets(campaign_id);
CREATE INDEX IF NOT EXISTS idx_assets_phase ON assets(phase);

-- Comments for documentation
COMMENT ON TABLE campaigns IS 'Marketing campaigns generated by users';
COMMENT ON TABLE assets IS 'Individual marketing assets (prompts) for each campaign';
COMMENT ON COLUMN campaigns.product_name IS 'Name of the product being marketed';
COMMENT ON COLUMN campaigns.language IS 'Language for design text (Arabic or English)';
COMMENT ON COLUMN campaigns.brand_vibe IS 'Brand colors and style preferences';
COMMENT ON COLUMN campaigns.consistency_guide IS 'Guide for maintaining visual consistency across assets';
COMMENT ON COLUMN assets.asset_id IS 'Original asset number (0-13)';
COMMENT ON COLUMN assets.phase IS 'Phase: identity, product, or social';
COMMENT ON COLUMN assets.aspect_ratio IS 'Image aspect ratio (e.g., 1:1, 16:9)';
